# Repo desc
owner: BlissRoms
repo: statuspage

sites:
  - name: Website
    url: https://blissroms.org
  - name: Downloads
    url: https://downloads.blissroms.org
  - name: API
    url: https://downloads.blissroms.org/api/


status-website:
  cname: status.blissroms.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BlissRoms Status Page
  introTitle: "BlissRoms Status Page"
  introMessage: This is the BlissRoms Site uptime status page
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://blissroms.org

commitMessages:
  commitAuthorName: "BlissRoms Bot"
  commitAuthorEmail: "bot@blissroms.org"
